# Generated by Django 5.2.10 on 2026-01-16 13:46

import django.db.models.deletion
import django_rest_auth.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontEnd',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, null=True)),
                ('fek', models.CharField(max_length=300, null=True)),
                ('fep', models.CharField(max_length=300, null=True)),
                ('rule', models.CharField(choices=[('Read', 'Read'), ('Write', 'write'), ('ReadWrite', 'ReadWrite')], max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('created_at_time', models.TimeField(auto_now_add=True, null=True)),
                ('updated_at_time', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=100, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Desativado', 'Desativado')], default='Activo', max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('created_at_time', models.DateField(auto_now_add=True, null=True)),
                ('updated_at_time', models.DateField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, null=True)),
            ],
            options={
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Desativado', 'Desativado')], max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('created_at_time', models.DateField(auto_now_add=True, null=True)),
                ('updated_at_time', models.DateField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField(blank=True, null=True)),
            ],
            options={
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('perfil', models.ImageField(blank=True, default='user.png', null=True, upload_to=django_rest_auth.models.profile_image_path)),
                ('username', models.CharField(max_length=255)),
                ('mobile', models.CharField(blank=True, default=None, max_length=55, null=True, unique=True)),
                ('is_verified_mobile', models.BooleanField(default=False)),
                ('counter', models.IntegerField(default=0)),
                ('email', models.EmailField(blank=True, default=None, max_length=255, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_provider', models.CharField(default='email', max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_rest_auth.idioma')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(default='-', max_length=100, null=True)),
                ('logo', models.FileField(blank=True, default='logo.png', upload_to=django_rest_auth.models.logo_path)),
                ('display_logo', models.BooleanField(blank=True, default=True, null=True)),
                ('display_bar', models.BooleanField(blank=True, default=True, null=True)),
                ('display_qr', models.BooleanField(blank=True, default=True, null=True)),
                ('rodape', models.CharField(max_length=2000, null=True)),
                ('disc_space', models.FloatField(default=1048576.0, null=True)),
                ('disc_used_space', models.FloatField(default=0.0, null=True)),
                ('disc_free_space', models.FloatField(default=1048576.0, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Desativado', 'Desativado')], default='Desativado', max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('created_at_time', models.DateField(auto_now_add=True, null=True)),
                ('updated_at_time', models.DateField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('admins', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, to='auth.group')),
                ('modelos', models.ManyToManyField(blank=True, to='contenttypes.contenttype')),
            ],
            options={
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EntidadeGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('created_at_time', models.DateField(auto_now_add=True, null=True)),
                ('updated_at_time', models.DateField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_rest_auth.entidade')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EntidadeUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('created_at_time', models.DateField(auto_now_add=True, null=True)),
                ('updated_at_time', models.DateField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_rest_auth.entidade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EntidadeModulo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Desativado', 'Desativado')], max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('created_at_time', models.DateField(auto_now_add=True, null=True)),
                ('updated_at_time', models.DateField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_rest_auth.entidade')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_rest_auth.modulo')),
            ],
            options={
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InputString',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_rest_auth.input')),
                ('string', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_rest_auth.string')),
            ],
            options={
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, null=True)),
                ('l_latitude', models.CharField(default='.', max_length=100, null=True)),
                ('l_longetude', models.CharField(default='.', max_length=100, null=True)),
                ('endereco', models.CharField(default='.', max_length=300, null=True)),
                ('rodape', models.CharField(default='.', max_length=600, null=True)),
                ('icon', models.CharField(default='.', max_length=100, null=True)),
                ('label', models.CharField(default='.', max_length=100, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Desativado', 'Desativado')], default='Desativado', max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('created_at_time', models.DateField(auto_now_add=True, null=True)),
                ('updated_at_time', models.DateField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_rest_auth.entidade')),
                ('groups', models.ManyToManyField(blank=True, default='.', to='auth.group')),
            ],
            options={
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Ficheiro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ficheiro', models.FileField(blank=True, null=True, upload_to='ficheiros')),
                ('size', models.FloatField()),
                ('modelo', models.CharField(max_length=100, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Desativado', 'Desativado')], default='Desactivado', max_length=100, null=True)),
                ('funcionalidade', models.CharField(choices=[('File', 'File'), ('Perfil', 'Perfil'), ('Logo', 'Logo'), ('Foto', 'Foto'), ('CapaSite', 'CapaSite')], default='File', max_length=100, null=True)),
                ('chamador', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('created_at_time', models.DateField(auto_now_add=True, null=True)),
                ('updated_at_time', models.DateField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('entidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_rest_auth.entidade')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_rest_auth.sucursal')),
            ],
            options={
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SucursalGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('created_at_time', models.DateField(auto_now_add=True, null=True)),
                ('updated_at_time', models.DateField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_rest_auth.sucursal')),
            ],
            options={
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SucursalUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('created_at_time', models.DateField(auto_now_add=True, null=True)),
                ('updated_at_time', models.DateField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_rest_auth.sucursal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SucursalUserGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('created_at_time', models.DateField(auto_now_add=True, null=True)),
                ('updated_at_time', models.DateField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_rest_auth.sucursal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TipoEntidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, null=True)),
                ('icon', models.FileField(blank=True, default='logo.png', upload_to=django_rest_auth.models.icon_path)),
                ('license', models.TextField(default='license')),
                ('label', models.CharField(max_length=100, null=True)),
                ('ordem', models.IntegerField(default=2)),
                ('crair_entidade', models.BooleanField(default=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Desativado', 'Desativado')], max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('created_at_time', models.DateField(auto_now_add=True, null=True)),
                ('updated_at_time', models.DateField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, to='auth.group')),
                ('modelos', models.ManyToManyField(blank=True, to='contenttypes.contenttype')),
            ],
            options={
                'permissions': (),
            },
        ),
        migrations.AddField(
            model_name='entidade',
            name='tipo_entidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_rest_auth.tipoentidade'),
        ),
        migrations.CreateModel(
            name='TipoEntidadeModulo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Desativado', 'Desativado')], max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('created_at_time', models.DateField(auto_now_add=True, null=True)),
                ('updated_at_time', models.DateField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_rest_auth.modulo')),
                ('tipo_entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_rest_auth.tipoentidade')),
            ],
            options={
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Traducao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chave', models.TextField(blank=True, null=True)),
                ('traducao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_rest_auth.idioma')),
            ],
            options={
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispositivo', models.TextField(null=True)),
                ('mobile', models.CharField(max_length=100, null=True)),
                ('info', models.TextField(null=True)),
                ('local_lat', models.CharField(max_length=100, null=True)),
                ('local_lon', models.CharField(max_length=100, null=True)),
                ('local_nome', models.CharField(max_length=100, null=True)),
                ('data', models.DateField(auto_now_add=True, null=True)),
                ('hora', models.TimeField(auto_now_add=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (),
            },
        ),
    ]
