# Generated by Django 5.2.10 on 2026-01-27 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('django_saas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verified',
            new_name='is_verified_email',
        ),
        migrations.AlterUniqueTogether(
            name='entidadegroup',
            unique_together={('entidade', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='sucursalgroup',
            unique_together={('sucursal', 'group')},
        ),
    ]
